### ISSUE TITLE
J2me loader

### ISSUE THREAD

**Issue by errotech** [schulle4u/awesome-android-accessibility#10]
https://play.google.com/store/apps/details?id=ru.playsoftware.j2meloader

https://f-droid.org/de/packages/ru.playsoftware.j2meloader/

Lädt J2mE-Software, die man früher auf mobiltelefonen installiert hat.
Geladene Software nicht auslesbar, App an sich ist zugänglich. Für Sehbehinderte sicher interessant.

**Comment by schulle4u** [comment]
Ich denke es macht wenig Sinn diese App aufzunehmen, da die eigentlichen Inhalte in dieser App unzugänglich sind. Sicher kann man mit einem Sehrest noch etwas damit anfangen, aber im Gegensatz zu z. B. einer Lupen-App hätte das für diese Liste keine Relevanz.

**Comment by errotech** [comment]
Gut, nachvollziehbar.

Gesendet von Mail für Windows 10

Von: Steffen Schultz
Gesendet: Donnerstag, 20. Mai 2021 09:47
An: schulle4u/awesome-android-accessibility
Cc: errotech; Author
Betreff: Re: [schulle4u/awesome-android-accessibility] J2me loader (#10)

Ich denke es macht wenig Sinn diese App aufzunehmen, da die eigentlichen Inhalte in dieser App unzugänglich sind. Sicher kann man mit einem Sehrest noch etwas damit anfangen, aber im Gegensatz zu z. B. einer Lupen-App hätte das für diese Liste keine Relevanz.
