### ISSUE TITLE
Total Commander

### ISSUE THREAD

**Issue by errotech** [schulle4u/awesome-android-accessibility#11]
Sicherlich einer der bekanntesten Dateimanager.

https://play.google.com/store/apps/details?id=com.ghisler.android.TotalCommander

**Comment by schulle4u** [comment]
Ah, den hatte ich gar nicht mehr auf dem Schirm, habe ich eingetragen.

**Comment by errotech** [comment]
Hatte mir den auch nur geladen, weil Huawei keinen gescheiten mitgeliefert hat.
Am 21.05.2021 10:03 schrieb Steffen Schultz ***@***.***>:
Ah, den hatte ich gar nicht mehr auf dem Schirm, habe ich eingetragen.
