### ISSUE TITLE
NotificationLog

### ISSUE THREAD

**Issue by errotech** [schulle4u/awesome-android-accessibility#15]
Protokolliert Benachrichtigungen:

https://f-droid.org/de/packages/de.jl.notificationlog/

**Comment by schulle4u** [comment]
Danke, ist eingetragen. Die Filterliste zum Ausblenden von Apps ist nicht ganz optimal zu nutzen, da einem die Auswahl einer App nicht angesagt wird. Man kann aber alternativ jede App einzeln über die weiteren Optionen ausblenden.

**Comment by errotech** [comment]
Wäre das Tool  nicht unter systemwerkzeuge besser aufgehoben?
Am 18.07.2021 19:39 schrieb Steffen Schultz ***@***.***>:

Danke, ist eingetragen. Die Filterliste zum Ausblenden von Apps ist nicht ganz optimal zu nutzen, da einem die Auswahl einer App nicht angesagt wird. Man kann aber alternativ jede App einzeln über die weiteren Optionen ausblenden.

**Comment by schulle4u** [comment]
Hmm, die Übergänge sind da manchmal fließend. Ich denke aber Systemwerkzeuge sind Apps, die das Aussehen oder die Verhaltensweise des Systems beeinflussen, also Launcher, Tastaturen etc. NotificationLog holt ja lediglich Informationen aus dem System.
