### ISSUE TITLE
Die Basis dieses Projekt als App

### ISSUE THREAD

**Issue by errotech** [schulle4u/awesome-android-accessibility#16]
https://play.google.com/store/apps/details?id=com.github.android

**Comment by schulle4u** [comment]
Ist eingetragen.

**Comment by errotech** [comment]
Das vereinfacht mir das Einreichen von Apps erheblich!
Am 19.07.2021 20:25 schrieb Steffen Schultz ***@***.***>:
Ist eingetragen.
