### ISSUE TITLE
Copy to clipboard

### ISSUE THREAD

**Issue by errotech** [schulle4u/awesome-android-accessibility#17]
Text per Teilen Menü in die Zwischenablage kopieren. Zumindest das modifizite Huawei Android bringt diese Funktion von Haus aus nicht mit
https://play.google.com/store/apps/details?id=com.robglez.copyshare.

**Comment by schulle4u** [comment]
Interessant, ich dachte immer es wäre ein Standard-Feature in Android. ISt eingetragen.

**Comment by errotech** [comment]
Einige Apps können das von Haus aus, andere, z.B. der google play store beim Teilen einer App, nicht. Hat unter einem Stock ROM auf einem Samsung anscheinend auch nicht ohne weiteres funktioniert.
Am 29.07.2021 10:30 schrieb Steffen Schultz ***@***.***>:

Interessant, ich dachte immer es wäre ein Standard-Feature in Android. ISt eingetragen.
