### ISSUE TITLE
ÖBB Scotty

### ISSUE THREAD

**Issue by errotech** [schulle4u/awesome-android-accessibility#18]
Quasi der Bahn Navigator für die österreichische bundesbahn. Wenn die App der Deutschen Bahn für Android auch so perfekt wäre ...

https://play.google.com/store/apps/details?id=de.hafas.android.oebb

**Comment by schulle4u** [comment]
Die Nutzer in den Rezensionen sind aber mal mindestens genauso am Schimpfen wie bei den deutschen Bahn-Apps. 😀 Danke, ist eingetragen.

**Comment by errotech** [comment]
Das sind die, die nicht an der Grenze wohne oder noch nie in Deutschland mit der Deutschen Bahn gefahren sind. Ich finde bei der ÖBB generell einige Konzepte besser, als bei der Deutschen Bahn. "Wir bauen für sie" anstatt "Grund dafür sind Bauarbeiten" klingt schon noch optimistischer, oder oder der Zug, mit dem wir nach Wien gefahren sind, war schon ausgelastet. In der durchsage wurde mitgeteilt, an welchem gleisabschnitt Passagiere denn bitte einsteigen sollten, weil in den entsprechenden Wägen doch Plätze frei waren...?
Am 29.07.2021 10:28 schrieb Steffen Schultz ***@***.***>:

Die Nutzer in den Rezensionen sind aber mal mindestens genauso am Schimpfen wie bei den deutschen Bahn-Apps. 😀 Danke, ist eingetragen.
