### ISSUE TITLE
Vorschlag einer App für Messaging, Kategorie Kommunikation

### ISSUE THREAD

**Issue by errotech** [schulle4u/awesome-android-accessibility#2]
Da unter den Netzwerken der Facebook-Klient gelistet ist, könntest du der Kategorie "Kommunikation" ja den Messenger hinzufügen, der sowohl unter IOS, als auch unter Android (sonst gäbs ja den Vorschlag nicht) zugänglich ist.

**Comment by schulle4u** [comment]
Danke für den Hinweis, ist hinzugefügt.
