### ISSUE TITLE
Ifttt

### ISSUE THREAD

**Issue by errotech** [schulle4u/awesome-android-accessibility#20]
https://play.google.com/store/apps/details?id=com.ifttt.ifttt

**Comment by schulle4u** [comment]
Warum auch immer mir Google Play trotz deutscher Spracheinstellung die Seite auf spanisch oder sowas anzeigt.. danke, ist eingetragen.

**Comment by errotech** [comment]
Die Beschreibung ist definitiv auf Spanisch, verstehe ich auch nicht.
Am 14.11.2021 10:18 schrieb Steffen Schultz ***@***.***>:
Warum auch immer mir Google Play trotz deutscher Spracheinstellung die Seite auf spanisch oder sowas anzeigt.. danke, ist eingetragen.
