### ISSUE TITLE
Core

### ISSUE THREAD

**Issue by errotech** [schulle4u/awesome-android-accessibility#22]
Offizielle und auf den ersten Blick bisher auch zugänglichste Remote-App für Kodi

https://f-droid.org/en/packages/org.xbmc.kore/

https://play.google.com/store/apps/details?id=org.xbmc.kore

**Comment by schulle4u** [comment]
Lässt sich die App im Zusammenspiel mit Kodi denn überhaupt selbstständig einrichten? Ich nehme mal an, dass die Remote-Funktionen standardmäßig inaktiv sind. Und das Screenreader-Addon wird ja leider nicht vom offiziellen Entwickler auf Kodi 19 angepasst, daher ist die Software momentan eher unbrauchbar. Fragt sich also, ob die App in der Liste überhaupt Sinn macht, wenn der Gegenpart wenn überhaupt nur mit Schwierigkeiten zugänglich ist.

**Comment by errotech** [comment]
Laut demjenigen, auf dessen GitHub profil ich das ganze gefunden habe, wirken die offiziellen Entwickler wohl schon mit. Aber jedenfalls ist es im offiziellen repo noch gar nicht verfügbar. Aber wir können uns die app zumindest mal vormerken, zumal, wenn es auf die KODi Versionen beim Nutzer nicht zwangsläufig ankommt, es auch mit KODi 18 und weiter runter funktioniert.
Am 27.12.2021 10:55 schrieb Steffen Schultz ***@***.***>:

Lässt sich die App im Zusammenspiel mit Kodi denn überhaupt selbstständig einrichten? Ich nehme mal an, dass die Remote-Funktionen standardmäßig inaktiv sind. Und das Screenreader-Addon wird ja leider nicht vom offiziellen Entwickler auf Kodi 19 angepasst, daher ist die Software momentan eher unbrauchbar. Fragt sich also, ob die App in der Liste überhaupt Sinn macht, wenn der Gegenpart wenn überhaupt nur mit Schwierigkeiten zugänglich ist.

**Comment by schulle4u** [comment]
Ich lasse das Issue mal geöffnet, sobald Kodi dann wieder offizielle Accessibility bekommt kann auch die App gern in die Liste.

**Comment by errotech** [comment]
Da es ja jetzt schon Anleitungen gibt, wie man den Screen wieder in Version 19 einbindet, zudem andere Nutzer vielleicht noch Version 18 benutzen, könnte man ja vielleicht noch mal überlegen, das ganze doch aufzunehmen.

> Lässt sich die App im Zusammenspiel mit Kodi denn überhaupt selbstständig einrichten? Ich nehme mal an, dass die Remote-Funktionen standardmäßig inaktiv sind. Und das Screenreader-Addon wird ja leider nicht vom offiziellen Entwickler auf Kodi 19 angepasst, daher ist die Software momentan eher unbrauchbar. Fragt sich also, ob die App in der Liste überhaupt Sinn macht, wenn der Gegenpart wenn überhaupt nur mit Schwierigkeiten zugänglich ist.
