### ISSUE TITLE
Mopria Scan

### ISSUE THREAD

**Issue by errotech** [schulle4u/awesome-android-accessibility#23]
Ermöglicht das Scannen über die meisten multifunktionsgeräte, über das heimnetzwerk. Das PDF, sofern man dieses Format auswählt, wird, wie auch unter Windows üblich, nicht als leserlicher Text gespeichert, das ist ja aber auch nicht der Sinn dieser App und man kann mit weiteren Apps dem auch entgegenwirken. Die Barrierefreiheit diese App ist auf jeden Fall gegeben!

https://play.google.com/store/apps/details?id=org.mopria.scan.application

**Comment by schulle4u** [comment]
Danke, habe es unter Büro einsortiert.
