### ISSUE TITLE
Spotiflyer

### ISSUE THREAD

**Issue by errotech** [schulle4u/awesome-android-accessibility#24]
Lädt Musik unter anderem von YouTube, YouTube Music, soundcloud und Spotify herunter. Ist wahrscheinlich nicht mit den Nutzungsbedingungen der jeweiligen Plattform bis auf soundcloud, weil man ja meines Wissens nach auch dort herunterladen kann, vereinbar, privatkopien sind in Deutschland aber rechtlich gestattet, wenn die gesetzeslage noch aktuell ist. Demnach stellt sich erstmal die Frage, ob diese Anwendung im rechtlichen Rahmen aufgenommen werden soll. Abgesehen davon funktioniert sie aber. Es folgt der downloadlink:

https://f-droid.org/packages/com.shabinder.spotiflyer

**Comment by schulle4u** [comment]
Ich denke das ist vertretbar, anders wäre es mit Apps die extra auf illegale Download- und Streaming-Angebote verweisen oder ähnliches. Im Grunde verletzt die App im Fall von Spotify noch nicht mal deren Nutzungsbedingungen, da zum Herunterladen widerum Youtube Music angezapft wird. Man bekommt also leider auch nie die beste Qualität.

**Comment by errotech** [comment]
Ich denke wenn ein Lied so gut ist, dass ich es in hoher Qualität hören möchte, kann ich es mir auch kaufen. Aber das habe ich gar nicht gelesen, dass der für den Download YouTube Music benutzt. Vielleicht habe ich das auch übersehen. Wüsste jetzt auch nicht exklusives, was es auf Spotify gibt, nicht aber auf YouTube.

Am 9. Januar 2022 14:32:30 MEZ schrieb Steffen Schultz ***@***.***>:
>Ich denke das ist vertretbar, anders wäre es mit Apps die extra auf illegale Download- und Streaming-Angebote verweisen oder ähnliches. Im Grunde verletzt die App im Fall von Spotify noch nicht mal deren Nutzungsbedingungen, da zum Herunterladen widerum Youtube Music angezapft wird. Man bekommt also leider auch nie die beste Qualität. >
>
>
>-- >
>Reply to this email directly or view it on GitHub:
>
>https://github.com/schulle4u/awesome-android-accessibility/issues/24#issuecomment-1008299131
>
>You are receiving this because you authored the thread.
>
>
>
>Message ID: ***@***.***>
Mit freundlichen Grüßen



E. Röder
