### ISSUE TITLE
Firefox: Ergänzung durch Quelle in f-droid

### ISSUE THREAD

**Issue by errotech** [schulle4u/awesome-android-accessibility#25]
https://f-droid.org/packages/org.mozilla.firefox

**Comment by schulle4u** [comment]
Firefox ist nicht mehr offiziell in F-Droid verfügbar, dafür ein Fork der sich [Fennec](https://f-droid.org/de/packages/org.mozilla.fennec_fdroid/) nennt. Basiert wohl auf dem aktuellsten Firefox-Release, kann ihn gern mit aufnehmen.

**Comment by errotech** [comment]
Für den Firefox musste ich eine extra Quelle hinzufügen, das stimmt. Ich hatte ja den Firefox über einen alternativen PlayStore Client installiert, für diesen wurde mir dann auch über f-droid eine Aktualisierung angeboten.

Am 9. Januar 2022 21:31:06 MEZ schrieb Steffen Schultz ***@***.***>:
>Firefox ist nicht mehr offiziell in F-Droid verfügbar, dafür ein Fork der sich [Fennec](https://f-droid.org/de/packages/org.mozilla.fennec_fdroid/) nennt. Basiert wohl auf dem aktuellsten Firefox-Release, kann ihn gern mit aufnehmen. >
>
>
>-- >
>Reply to this email directly or view it on GitHub:
>
>https://github.com/schulle4u/awesome-android-accessibility/issues/25#issuecomment-1008368764
>
>You are receiving this because you authored the thread.
>
>
>
>Message ID: ***@***.***>
Mit freundlichen Grüßen



E. Röder
