### ISSUE TITLE
satellite – weltweit mobil telefonieren

### ISSUE THREAD

**Issue by errotech** [schulle4u/awesome-android-accessibility#3]
Satellite bietet kostenlos eine Handynummer (Unter IOS hat sie den Zusatz "Handy in der App" und monatlich 100 Freiminuten in die EU und viele, weitere Staaten.

https://play.google.com/store/apps/details?id=de.sipgate.app.satellite

**Comment by schulle4u** [comment]
Auch das ist aufgenommen. Habe dann gleich noch Linphone als Telefonie-App mit eingetragen.
