### ISSUE TITLE
Termux

### ISSUE THREAD

**Issue by errotech** [schulle4u/awesome-android-accessibility#32]
GNU-Apps unter Android ausführen. In den vordefinierten Quellen befinden sich Pakete, die für ARM oder vielleicht auch speziell für Termux kompiliert und angepasst wurden. Es ist auch möglich, Das Gerät an sich anzusteuern (Aufnahme oder Fotos machen, Telefonanrufe tätigen, Gerät vibrieren lassen etc.). Das Ganze kann man natürlich durch Scripts schön ausreizen.

Habe die App schon Länger im Einsatz, war oder bin mir nicht ganz sicher, ob man die hier aufnehmen will. Falls ja:

https://f-droid.org/en/packages/com.termux/

**Comment by schulle4u** [comment]
Hmm, da bin ich mir auch nicht sicher. Prinzipiell ist die App bedienbar, aber es gibt z. B. kein automatisches Sprachfeedback wenn man einen Befehl absetzt, sodass man erst umständlich mit der Zeilennavigation hantieren muss um die Terminal-Ausgabe zu sehen. Ist also eher etwas für erfahrene Anwender, die mit solchen Problemen klarkommen. Würde es daher im Moment eher nicht mit aufnehmen.
