### ISSUE TITLE
Ergänzung Transistor

### ISSUE THREAD

**Issue by errotech** [schulle4u/awesome-android-accessibility#34]
Soll Informationen jetzt wohl als Json speichern und kann nun auch auf radio-browser.info zugreifen (letzteres kann ich bestätigen).

**Comment by schulle4u** [comment]
Danke für die Erinnerung, habe den Eintrag aktualisiert. Ich nutze Transistor sogar noch, hatte nur vergessen den Text in der Liste anzupassen.
