### ISSUE TITLE
Newpipe als alternativer Youtube-Klient

### ISSUE THREAD

**Issue by errotech** [schulle4u/awesome-android-accessibility#4]
newPipe, zu  finden in F-Droid, ist ein Klient für Youtube und Soundcloud. das besondere insbesondere für Youtube-Wiedergaben ist die möglichkeit, sowohl videos, als auch nur die Audiospur (dann auch im Hintergrund und mit ausgeschaltetem Bildschirm) wiederzugeben. Zudem kommt hinzu, dass keine Informationen über den Nutzer und das Video, das er sich anschaut, an Google übergeben wird, sondern newpipe sich direkt des eigentlichen Videolinks bedient. Downloads sind ebenfalls möglich.
Abos kann man über die App abschließen oder man lädt sich die Datei mit den vorhandenen Abos herunter, falls man ein Google-Konto hat und einen oder mehrere youtube-Kanäle aboniert hat.
Größtenteils sind die Schaltflächen beschriftet, lediglich für die Mediensteuerung für die Hintergrundwiedergabe kann das Aktivieren der Element-ID-Beschriftung nützlich sein.

**Comment by schulle4u** [comment]
Danke, ist eingetragen. Die App hat sich wirklich gut entwickelt, kenne die noch mit etwas schlechterer Bedienbarkeit.

**Comment by errotech** [comment]
Als ich sie September 2018 das erste Mal genutzt hab, war sie  bereits zugänglich.

Eric

Von: Steffen Schultz
Gesendet: Mittwoch, 20. Mai 2020 13:44
An: schulle4u/awesome-android-accessibility
Cc: errotech; Author
Betreff: Re: [schulle4u/awesome-android-accessibility] Newpipe alsalternativer Youtube-Klient (#4)

Danke, ist eingetragen. Die App hat sich wirklich gut entwickelt, kenne die noch mit etwas schlechterer Bedienbarkeit.
