### ISSUE TITLE
Tasker

### ISSUE THREAD

**Issue by errotech** [schulle4u/awesome-android-accessibility#53]
Ist meines Wissens nach nicht OpenSource, wie angegeben.

**Comment by schulle4u** [comment]
Recht hast du, ist sogar kostenpflichtig. Habe den Eintrag korrigiert. Ich schau gleich mal woher der Fehler kommt, habe die App selbst nicht im Einsatz.

**Comment by schulle4u** [comment]
Ah, [der Julian war schuld](#32). Aber hätte natürlich auch besser hingucken können. 😀
