### ISSUE TITLE
Network Scanner

### ISSUE THREAD

**Issue by errotech** [schulle4u/awesome-android-accessibility#57]
Ning zeigt mir irgendwie keine Hostamen an. Dieses Tool wurde zuletzt vor neun Jahren aktualisiert, funktioniert aber ohne Probleme.
https://f-droid.org/packages/com.unwind.networkmonitor/

**Comment by errotech** [comment]
Habe sie jetzt ein paar mal benutzt, finde, die taugt was

**Comment by schulle4u** [comment]
Na dann trage ich sie doch glatt mit ein. 🙂 Manche Seiten sehen etwas seltsam aus wie z. B. der Port-Scan, da könnte der Entwickler etwas bei der Anordnung der Auswahlschalter für häufig genutzte Domains, Ports etc optimieren. Aber prinzipiell ist die App gut bedienbar.
