### ISSUE TITLE
Candle - Navigations App für Blinde

### ISSUE THREAD

**Issue by freegroup** [schulle4u/awesome-android-accessibility#62]
Über diese App
Entdecken Sie eine nahtlose und barrierefreie Navigation mit unserer App, die speziell für blinde und sehbehinderte Benutzer entwickelt wurde. Mit unserer innovativen Lösung können Sie mühelos Points of Interest (POIs) speichern und sicher zu Ihren gewünschten Zielen navigieren. Unsere App wurde mit vollständiger Talkback-Unterstützung entwickelt und gewährleistet eine vollständige Voice-Over-Funktionalität, was sie besonders benutzerfreundlich für Menschen mit Sehbehinderungen macht.

Github: https://github.com/freegroup/candle
Google: https://play.google.com/store/apps/details?id=de.freegroup.candle

Würde mich über eine Auflistung in deiner AwesomeList freuen.

**Comment by schulle4u** [comment]
Danke, habe ich in die Liste aufgenommen. Nur so aus Neugier: Welche Datenbasis nutzt du für die öffentlichen Pois? Habe z. B. in meiner Nähe eine Apotheke gesehen, die schon seit sicher 10 Jahren geschlossen hat. 😯

**Comment by schulle4u** [comment]
@freegroup Wird das Projekt noch weiterentwickelt? Die App ist seit einiger Zeit nicht mehr via Google Play erreichbar.
