### ISSUE TITLE
Foss warn: quelloffene Alternative zu Warnapps wie Nina

### ISSUE THREAD

**Issue by errotech** [schulle4u/awesome-android-accessibility#64]
https://f-droid.org/packages/de.nucleus.foss_warn/

**Comment by schulle4u** [comment]
Ist zwar prinzipiell bedienbar, hat aber leider einige Buttons die gar keine oder zumindest keine logische Beschriftung haben, also auch nicht mit Element-ID sinnvoll lesbar sind. Daher würde ich die App erst mal nicht mit aufnehmen wollen.

**Comment by errotech** [comment]
Werde dem Entwickler mal schreiben.

Am 5. Februar 2024 09:58:32 MEZ schrieb Steffen Schultz ***@***.***>:
