### ISSUE TITLE
Appvorschlag für Banking

### ISSUE THREAD

**Issue by errotech** [schulle4u/awesome-android-accessibility#7]
Die Bestsign-App der Postbank ist mittels Talkback gut bedienbar. Diese kann zur Legitimierung von Bankaufträgen genutzt werden.

**Comment by schulle4u** [comment]
In der Beschreibung steht, dass BestSign bereits Teil der App Postbank Finanzassistent ist, und man die zweite App dann eigentlich nicht braucht. Ist die eigentliche Postbank-App auchzugänglich? Dann sollte man vielleicht lieber diese eintragen, macht doch mehr Sinn. Bin selbst Sparkassenkunde.

**Comment by errotech** [comment]
Müsste ich noch mal nachgucken, als ich sie das letzte Mal benutzen wollte, war das auf jeden Fall nicht der Fall.
Am 26.08.2020 17:31 schrieb Steffen Schultz <notifications@github.com>:

In der Beschreibung steht, dass BestSign bereits Teil der App Postbank Finanzassistent ist, und man die zweite App dann eigentlich nicht braucht. Ist die eigentliche Postbank-App auchzugänglich? Dann sollte man vielleicht lieber diese eintragen, macht doch mehr Sinn. Bin selbst Sparkassenkunde.

**Comment by schulle4u** [comment]
@errotech Hast du bezüglich Postbank noch etwas herausfinden können?

**Comment by errotech** [comment]
Letztens nochmal getestet und immernoch nicht zufrieden.
Gesendet von Mail für Windows 10

Von: Steffen Schultz
Gesendet: Sonntag, 15. November 2020 23:09
An: schulle4u/awesome-android-accessibility
Cc: errotech; Mention
Betreff: Re: [schulle4u/awesome-android-accessibility] Appvorschlag für Banking (#7)

@errotech Hast du bezüglich Postbank noch etwas herausfinden können?
