### ISSUE TITLE
Ariane

### ISSUE THREAD

**Issue by errotech** [schulle4u/awesome-android-accessibility#9]
Ein Klient für das Gemini-Protokoll.

https://play.google.com/store/apps/details?id=oppen.gemini.ariane

**Comment by schulle4u** [comment]
Danke, ist eingetragen. Schon witzig, dass es sowas wie Gopher in weiterentwickelter Form immer noch gibt.

**Comment by errotech** [comment]
Die TAZ hat wohl noch eine Goopher-Seite, ebenso gibt’s dafür die englischsprachige Wikipedia, kann ich unter Win98 im alten IE mal testen. Zudem will ich mal gucken, welcher Browser denn dort für Android geeignet ist.

Gesendet von Mail für Windows 10

Von: Steffen Schultz
Gesendet: Donnerstag, 6. Mai 2021 12:28
An: schulle4u/awesome-android-accessibility
Cc: errotech; Author
Betreff: Re: [schulle4u/awesome-android-accessibility] Ariane (#9)

Danke, ist eingetragen. Schon witzig, dass es sowas wie Gopher in weiterentwickelter Form immer noch gibt.
